stage 2

diff --git a/search-engine-app/ui/.gitlab-ci.yml b/search-engine-app/ui/.gitlab-ci.yml
--- a/search-engine-app/ui/.gitlab-ci.yml
+++ b/search-engine-app/ui/.gitlab-ci.yml
@@ -44,10 +44,77 @@ build:
 
 test:
   stage: test
-  script:
-    - exit 0
+  variables:
+    KUBE_NAMESPACE: test
+    host: $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG
+    TILLER_NAMESPACE: kube-system
+    CI_APPLICATION_TAG: $CI_COMMIT_REF_SLUG
+    name: $CI_ENVIRONMENT_SLUG
+  environment:
+    name: test/$CI_PROJECT_PATH/$CI_COMMIT_REF_NAME
+    url: http://$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG
+    auto_stop_in: 5 mins
   only:
-    - branches
+    refs:
+      - branches
+    kubernetes: active
+  except:
+    - master
+  before_script:
+    # installing dependencies
+    - apk add -U openssl curl tar gzip bash ca-certificates git
+    - wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
+    - wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.23-r3/glibc-2.23-r3.apk
+    - apk add glibc-2.23-r3.apk
+    - curl https://storage.googleapis.com/pub/gsutil.tar.gz | tar -xz -C $HOME
+    - export PATH=${PATH}:$HOME/gsutil
+    - curl https://kubernetes-helm.storage.googleapis.com/helm-v2.13.1-linux-amd64.tar.gz | tar zx
+    - mv linux-amd64/helm /usr/bin/
+    - helm version --client
+    - curl  -o /usr/bin/sync-repo.sh https://raw.githubusercontent.com/kubernetes/helm/master/scripts/sync-repo.sh
+    - chmod a+x /usr/bin/sync-repo.sh
+    - curl -L -o /usr/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
+    - chmod +x /usr/bin/kubectl
+    - kubectl version --client
+    # ensuring namespace
+    - kubectl describe namespace "$KUBE_NAMESPACE" || kubectl create namespace "$KUBE_NAMESPACE"
+
+    # installing Tiller
+    - echo "Checking Tiller..."
+    - helm init --force-upgrade
+    - kubectl rollout status -n "$TILLER_NAMESPACE" -w "deployment/tiller-deploy"
+    - >
+      if ! helm version --debug; then
+        echo "Failed to init Tiller."
+        exit 1
+      fi
+  script:
+    - export track="${1-stable}"
+    - >
+      if [[ "$track" != "stable" ]]; then
+        name="$name-$track"
+      fi
+    - echo "Clone deploy repository..."
+    - git clone https://gitlab.se-project.tk/$CI_PROJECT_NAMESPACE/search-engine-deploy.git
+    - echo "Download helm dependencies..."
+    - helm dep update search-engine-deploy/search-engine
+    - echo "Deploy helm release $name to $KUBE_NAMESPACE"
+    - echo "Upgrading existing release..."
+    - echo "helm upgrade --install --wait --set ui.ingress.host="$host" --set $CI_PROJECT_NAME.image.tag="$CI_APPLICATION_TAG" --namespace="$KUBE_NAMESPACE" --version="$CI_PIPELINE_ID-$CI_JOB_ID" "$name" search-engine-deploy/search-engine/"
+    - >
+      helm upgrade \
+        --install \
+        --wait \
+        --set ui.ingress.host="$host" \
+        --set $CI_PROJECT_NAME.image.tag="$CI_APPLICATION_TAG" \
+        --namespace="$KUBE_NAMESPACE" \
+        --version="$CI_PIPELINE_ID-$CI_JOB_ID" \
+        "$name" \
+        search-engine-deploy/search-engine/
+    - kubectl exec --namespace $KUBE_NAMESPACE $(kubectl get pods --namespace $KUBE_NAMESPACE | grep $name-$CI_PROJECT_NAME | awk '{print $1}') -- /bin/sh -c 'cd /app && pip install -r requirements-test.txt &&  python -m unittest discover -s tests/'
+  after_script:
+    - helm delete "$name" --purge
+    - helm ls
 
 release:
   stage: release
@@ -152,6 +219,7 @@ review:
         --version="$CI_PIPELINE_ID-$CI_JOB_ID" \
         "$name" \
         search-engine-deploy/search-engine/
+
 stop_review:
   stage: cleanup
   variables:
@@ -186,4 +254,3 @@ stop_review:
     - kubectl version --client
   script:
     - helm delete "$name" --purge
-...
